app/Http/routes.php
<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Authorization, Content-Type' );
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers:  X-Requested-With, Content-Type, X-Auth-Token, Origin, Authorization');
header('Access-Control-Allow-Methods:GET,PUT,POST,DELETE');

/*
|--------------------------------------------------------------------------
| DEBUT PARTIE FRONT-OFFICE
|
*/
Route::get('/', function () {
    return view('home');
})->name('home');

Route::get('/abonnement', function () {
    return view('abonnement');
});

Route::get('/diapo', function () {
    return view('diapo');
})->name('diapo');
/*Route::get('/landing', function () {
    return view('landing');
})->name('landing');*/

/*Route::get('/profil', function () {
    return view('profil');
});*/

/*Route::get('/pre-register', function () {
    return view('pre-register');
});*/

/*Route::get('/register', function () {
    return view('register');
});*/

/*Route::get('/login', function () {
    return view('login');
});*/

Route::get('auth/login', 'Auth\AuthController@getLogin')
    ->name('auth_login');

Route::get('/contact', function () {
    return view('contact');
});

Route::get('/faq', function () {
    return view('faq');
});

Route::get('/register', 'RegisterController@index');
Route::post('/register', 'RegisterController@create');

Route::get('forgetpassword', 'Auth\AuthController@forgetPassword')->name('forget_password');

Route::post('/abonnement', 'RegisterController@registerAbonnement');
Route::get('/abonnement', 'RegisterController@abonnement');
Route::get('abonnement/{id}', 'RegisterController@abonnement');


Route::get('/confidentialite', function () {
    return view('confidentialite');
})->name('confidentialite');

Route::get('/presentation', 'PagesController@displayPresentation');
Route::get('/mentions-legales', 'PagesController@displayMentions')
    ->name('mentions-legales');
Route::get('/cgv', 'PagesController@displayCgv')
    ->name('cgv');

Route::resource('pages', 'PagesController', ['only' => ['index','edit','update']]);

/*
|--------------------------------------------------------------------------
| FIN PARTIE FRONT-OFFICE
|
*/

/*
|--------------------------------------------------------------------------
| DEBUT PARTIE BACK-OFFICE
|
*/


Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
    Route::get('', 'StatsController@index')->name('admin_dashboard');

    Route::resource('pages', 'PagesController', ['only' => ['index','edit','update']]);

    Route::get('abonnement/{id}', 'UsersController@abonnement')
        ->where('id', '[0-9]+');

    Route::post('abonnement/{id}', 'UsersController@abonnement_update')
        ->name('abonnement_update')
        ->where('id', '[0-9]+');



    Route::get('abonnements/', 'UsersController@abonnements');


    Route::group(['prefix' => 'user'],   function()
    {
        Route::get('delete/{id}', 'UsersController@destroy')
            ->where('id', '[0-9]+');

        Route::post('update/{id}', 'UsersController@update')
            ->name('user_update')
            ->where('id', '[0-9]+');

        Route::post('update/{id}', 'UsersController@profile_update')
            ->name('profile_update')
            ->where('id', '[0-9]+');


        Route::get('edit/{id}', 'UsersController@edit')
            ->name('user_update')
            ->where('id', '[0-9]+');


        // Registration routes...
        Route::get('auth/register', 'Auth\AuthController@getRegister');
        Route::post('auth/register', 'Auth\AuthController@postRegister')
            ->name('register');

        Route::post('store', 'UsersController@store');
        Route::get('profile', 'UsersController@profile');

        Route::get('create', 'UsersController@create')
            ->name('user_create');

        Route::get('{id}', 'UsersController@show')
            ->name('user_show')
            ->where('id', '[0-9]+');

        Route::get('/', 'UsersController@index');
    });

    Route::get('stats/{periode}', 'StatsController@index')
        ->where('periode', '[DWMY]');
});



/*
|--------------------------------------------------------------------------
| FIN PARTIE BACK-OFFICE
|
*/

/*
|--------------------------------------------------------------------------
| DEBUT PARTIE API
|
*/
Route::group(['prefix' => 'api'],  function ()
{
  Route::group(['prefix' => 'v1'],   function()
  {
    Route::group(['prefix' => 'auth'],   function()
    {
      Route::post('login', 'Auth\AuthController@authentication')
        ->name('api_authenticate');
      Route::get('login', function() {
          return Redirect::to('http://ipssi-lyon.fr:8080');
      })->name('api_login_angular');
      Route::post('logout', 'Auth\AuthController@getLogout')
        ->name('api_getLogout');
    });

    //PARTIE USER
    Route::get('user/{id?}', 'Api\UsersApiController@show');
    Route::put('user/edit/{id}', 'Api\UsersApiController@update');
    Route::get('user/invoice/{id}', 'Api\UsersApiController@inVoice');

    Route::get('timebyperiod/{id}/{dateOne}/{dateTwo}', 'Api\UsersApiController@timeByPeriod');

    //PARTIE ABONNEMENT
    Route::get('abonnement/show/{id?}', 'Api\AbonnementsApiController@show');

    Route::post('table', 'Api\TablesApiController@create');
    Route::get('table', 'Api\TablesApiController@getAll');
    Route::get('table/{id}', 'Api\TablesApiController@get');
    Route::put('table/{id}', 'Api\TablesApiController@update');
    Route::delete('table/{id}', 'Api\TablesApiController@destroy');

    Route::post('row', 'Api\RowsApiController@create');
    Route::put('row/{id}', 'Api\RowsApiController@update');
    Route::delete('row/{idtable}/{id}', 'Api\RowsApiController@destroy');

    //Route::post('columns', 'Api\ColumnsApiController@update');
  });
});
/*
|--------------------------------------------------------------------------
| FIN PARTIE API
|
*/

resources/views/admin.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $page_title or "AdminLTE Dashboard" }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ URL::asset("admin-lte/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ URL::asset("admin-lte/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link href="{{ URL::asset("admin-lte/dist/css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue">
<div class="wrapper">

<!-- Header -->
@include('header')

<!-- Sidebar -->
@include('sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $page_title or "Page Title" }}
                <small>{{ $page_description or null }}</small>
            </h1>
            <!-- You can dynamically generate breadcrumbs here -->
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                <li class="active">Here</li>
            </ol>
        </section>



        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')

            <!-- Infos user -->
            @include('userinfos')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Footer -->
    @include('footer')

</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.1.3 -->
<script src="{{ URL::asset ("admin-lte/plugins/jQuery/jquery-2.2.3.min.js") }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ URL::asset ("admin-lte/bootstrap/js/bootstrap.min.js") }}" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="{{ URL::asset ("admin-lte/dist/js/app.min.js") }}" type="text/javascript"></script>
<!-- ChartJS 1.0.1 -->
<script src="{{ URL::asset ("admin-lte/plugins/chartjs/Chart.min.js") }}"></script>
<!-- Optionally, you can add Slimscroll and FastClick plugins.
      Both of these plugins are recommended to enhance the
      user experience -->

<script>
    $(function () {
        /* ChartJS
         * -------
         * Here we will create a few charts using ChartJS
         */

        //--------------
        //- AREA CHART -
        //--------------

        // Get context with jQuery - using jQuery's .get() method.
        var areaChartCanvas = $("#areaChart").get(0).getContext("2d");
        // This will get the first returned node in the jQuery collection.
        var areaChart = new Chart(areaChartCanvas);

        var areaChartData = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [
                {
                    label: "Electronics",
                    fillColor: "rgba(210, 214, 222, 1)",
                    strokeColor: "rgba(210, 214, 222, 1)",
                    pointColor: "rgba(210, 214, 222, 1)",
                    pointStrokeColor: "#c1c7d1",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: [65, 59, 80, 81, 56, 55, 40]
                },
                {
                    label: "Digital Goods",
                    fillColor: "rgba(60,141,188,0.9)",
                    strokeColor: "rgba(60,141,188,0.8)",
                    pointColor: "#3b8bba",
                    pointStrokeColor: "rgba(60,141,188,1)",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(60,141,188,1)",
                    data: [28, 48, 40, 19, 86, 27, 90]
                }
            ]
        };

        var areaChartOptions = {
            //Boolean - If we should show the scale at all
            showScale: true,
            //Boolean - Whether grid lines are shown across the chart
            scaleShowGridLines: false,
            //String - Colour of the grid lines
            scaleGridLineColor: "rgba(0,0,0,.05)",
            //Number - Width of the grid lines
            scaleGridLineWidth: 1,
            //Boolean - Whether to show horizontal lines (except X axis)
            scaleShowHorizontalLines: true,
            //Boolean - Whether to show vertical lines (except Y axis)
            scaleShowVerticalLines: true,
            //Boolean - Whether the line is curved between points
            bezierCurve: true,
            //Number - Tension of the bezier curve between points
            bezierCurveTension: 0.3,
            //Boolean - Whether to show a dot for each point
            pointDot: false,
            //Number - Radius of each point dot in pixels
            pointDotRadius: 4,
            //Number - Pixel width of point dot stroke
            pointDotStrokeWidth: 1,
            //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
            pointHitDetectionRadius: 20,
            //Boolean - Whether to show a stroke for datasets
            datasetStroke: true,
            //Number - Pixel width of dataset stroke
            datasetStrokeWidth: 2,
            //Boolean - Whether to fill the dataset with a color
            datasetFill: true,
            //String - A legend template
            legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",
      //Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
      maintainAspectRatio: true,
      //Boolean - whether to make the chart responsive to window resizing
      responsive: true
    };

    //Create the line chart
    areaChart.Line(areaChartData, areaChartOptions);

    //-------------
    //- LINE CHART -
    //--------------
    var lineChartCanvas = $("#lineChart").get(0).getContext("2d");
    var lineChart = new Chart(lineChartCanvas);
    var lineChartOptions = areaChartOptions;
    lineChartOptions.datasetFill = false;
    lineChart.Line(areaChartData, lineChartOptions);

    //-------------
    //- PIE CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var pieChartCanvas = $("#pieChart").get(0).getContext("2d");
    var pieChart = new Chart(pieChartCanvas);
    var PieData = [
      {
        value: 700,
        color: "#f56954",
        highlight: "#f56954",
        label: "Chrome"
      },
      {
        value: 500,
        color: "#00a65a",
        highlight: "#00a65a",
        label: "IE"
      },
      {
        value: 400,
        color: "#f39c12",
        highlight: "#f39c12",
        label: "FireFox"
      },
      {
        value: 600,
        color: "#00c0ef",
        highlight: "#00c0ef",
        label: "Safari"
      },
      {
        value: 300,
        color: "#3c8dbc",
        highlight: "#3c8dbc",
        label: "Opera"
      },
      {
        value: 100,
        color: "#d2d6de",
        highlight: "#d2d6de",
        label: "Navigator"
      }
    ];
    var pieOptions = {
      //Boolean - Whether we should show a stroke on each segment
      segmentShowStroke: true,
      //String - The colour of each segment stroke
      segmentStrokeColor: "#fff",
      //Number - The width of each segment stroke
      segmentStrokeWidth: 2,
      //Number - The percentage of the chart that we cut out of the middle
      percentageInnerCutout: 50, // This is 0 for Pie charts
      //Number - Amount of animation steps
      animationSteps: 100,
      //String - Animation easing effect
      animationEasing: "easeOutBounce",
      //Boolean - Whether we animate the rotation of the Doughnut
      animateRotate: true,
      //Boolean - Whether we animate scaling the Doughnut from the centre
      animateScale: false,
      //Boolean - whether to make the chart responsive to window resizing
      responsive: true,
      // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
      maintainAspectRatio: true,
      //String - A legend template
      legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"
    };
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    pieChart.Doughnut(PieData, pieOptions);

    //-------------
    //- BAR CHART -
    //-------------
    var barChartCanvas = $("#barChart").get(0).getContext("2d");
    var barChart = new Chart(barChartCanvas);
    var barChartData = areaChartData;
    barChartData.datasets[1].fillColor = "#00a65a";
    barChartData.datasets[1].strokeColor = "#00a65a";
    barChartData.datasets[1].pointColor = "#00a65a";
    var barChartOptions = {
      //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
      scaleBeginAtZero: true,
      //Boolean - Whether grid lines are shown across the chart
      scaleShowGridLines: true,
      //String - Colour of the grid lines
      scaleGridLineColor: "rgba(0,0,0,.05)",
      //Number - Width of the grid lines
      scaleGridLineWidth: 1,
      //Boolean - Whether to show horizontal lines (except X axis)
      scaleShowHorizontalLines: true,
      //Boolean - Whether to show vertical lines (except Y axis)
      scaleShowVerticalLines: true,
      //Boolean - If there is a stroke on each bar
      barShowStroke: true,
      //Number - Pixel width of the bar stroke
      barStrokeWidth: 2,
      //Number - Spacing between each of the X value sets
      barValueSpacing: 5,
      //Number - Spacing between data sets within X values
      barDatasetSpacing: 1,
      //String - A legend template
      legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].fillColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",
      //Boolean - whether to make the chart responsive
      responsive: true,
      maintainAspectRatio: true
    };

    barChartOptions.datasetFill = false;
    barChart.Bar(barChartData, barChartOptions);
  });
</script>
</body>
</html>

resources/views/cgv.blade.php
@extends('layouts.site-layout')

@section('title', 'Conditions Générales de Vente')

@section('content')


    <div class="container presentation" style="padding-top:20px;">
    	<div class="row" id="cgv">
    		{!! $cgv->content !!}
    	</div>
	   
	</div>

@stop

resources/views/footer.blade.php
<footer class="main-footer" style="background-color: #3c8dbc">
    <!-- To the right -->

    <!-- Default to the left -->
    <p style="color: white"><strong>Copyright © 2016 <a href="#">Company</a></strong> All rights reserved.</p>
</footer>

resources/views/header.blade.php
<!-- Main Header -->
<header class="main-header">
    <!-- Logo -->
        <a href="#" class="logo"><b><img src="/img/logo-intersession.png" alt="logo-BMS" style="height:45px;"></b></a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">John Doe</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <p>
                                John Doe - Web Developer
                                <small>Member since Sep. 2016</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="/admin/user/profile" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="/" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/mentions-legales.blade.php
@extends('layouts.site-layout')

@section('title', 'Mentions Légales')

@section('content')


    <div class="container presentation" style="padding-top:20px;">
    	<div class="row" id="mentions">
    		{!! $mentions->content !!}
    	</div>
	   
	</div>

@stop

resources/views/pages-index.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel</title>
    <meta charset="UTF-8">

    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    <title>{{ $page_title or "BMS Dashboard" }}</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{{ URL::asset("admin-lte/bootstrap/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{{ URL::asset("admin-lte/dist/css/AdminLTE.min.css")}}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset("admin-lte/dist/css/skins/skin-blue.min.css")}}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ URL::asset("admin-lte/dist/css/AdminLTE.min.css") }}"/>
        <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ URL::asset("admin-lte/dist/css/skins/_all-skins.min.css") }}"/>

</head>
<body class="skin-blue">
    <div class="wrapper">

        <!-- Header -->
        @include('header')

        <!-- Sidebar -->
        @include('sidebar')
        <div class="container">
            <div class="content">
                <div class="box">
                    <div class="box-header">
                        <h3>Liste des pages</h3>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-striped">
                            <thead>
                              <tr>
                                <th>Nom de la page</th>
                                <th>Action</th>
                              </tr>
                            </thead>
                                @foreach ($pages as $page)
                                    <tr>
                                        <td>{{ $page->name }}</td>
                                        <td>{!! link_to_route('pages.edit', 'Modifier', [$page->id], ['class' => 'editer']) !!}</td>
                                    </tr>
                                @endforeach
                        </table>
                    </div>
                </div>                
            </div>
        </div>
    <!-- Footer -->
    @include('footer')
    </div>
</body>
</html>

resources/views/presentation.blade.php
@extends('layouts.site-layout')

@section('title', 'Présentation')

@section('content')
	<div class="row">
		<div class="col s12 m12">
			<div id="owl-presentation" class="owl-carousel owl-theme">
				<div class="item"><img src="{{ URL::asset('img/presentation1.jpg') }}" alt="image1" title="image1"></div>
				<div class="item"><img src="{{ URL::asset('img/presentation2.jpg') }}" alt="image2" title="image2"></div>
				<div class="item"><img src="{{ URL::asset('img/presentation3.jpg') }}" alt="image3" title="image3"></div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m12">
			<h1 style="text-align: center"></h1>
			<div class="section-title">
				<h2>Présentation de l'entreprise BMS<span class="dark">BMS</span></h2>
			</div> <!-- .section-title ends -->
		</div>
	</div>
	<div class="container presentation">
		<div class="row">
			<div class="col s12 m12">
				<p>{!! $presentationGenerale->content !!}</p>
			</div>
		</div>
	</div>
	<div class="clear"></div>
	<div class="container">
	<div class="clear"></div>
	<section class="service section-block">
		<div class="section-title">
			<h2>Nos Avantages<span class="dark">BMS</span></h2>
		</div> <!-- .section-title ends -->

		<div class="container">
			<div class="row section-content">
				<div class="col m4 col s6">
					<div class="icon-block"><i class="fa fa-database"></i></div>
					<h3>Base de données Puissante</h3>

						{!! $service1->content !!}

				</div> <!-- .col-md-4 col-sm-6 ends -->

				<div class="col m4 col s6">
					<div class="icon-block"><i class="fa fa-cogs"></i></div>
					<h3>Constructeur d'application intuitif</h3>

						{!! $service2->content !!}

				</div> <!-- .col-md-4 col-sm-6 ends -->

				<div class="col m4 col s6">
					<div class="icon-block"><i class="fa fa-shield"></i></div>
					<h3>Sécurisé, fiable et évolutif</h3>

						{!! $service2->content !!}

				</div> <!-- .col-md-4 col-sm-6 ends -->

				<div class="col m4 col s6">
					<div class="icon-block"><i class="fa fa-fighter-jet"></i></div>
					<h3>Performance de déploiement</h3>
					<p>
						Mnaoare kese hai tu bata more manoorate tomader kase omon bosease dekho na tomader kase jabo to chole kivabe jete hbe bolona bondhu.
					</p>
				</div> <!-- .col-md-4 col-sm-6 ends -->

				<div class="col m4 col s6">
					<div class="icon-block"><i class="fa fa-cloud"></i></div>
					<h3>Hebergé sur un cloud sécurisé</h3>
					<p>
						Takale tumi ami hotath onno deshe chole ase mon hariye bolse asi kivabe to janina make niye tomar majhe kiemn chle je tumi ta bolona ar koto kivabe.
					</p>
				</div> <!-- .col-md-4 col-sm-6 ends -->

				<div class="col m4 col s6">
					<div class="icon-block"><i class="fa fa-shopping-cart"></i></div>
					<h3>Coût modulable pour tous les budgets</h3>
					<p>
						Chupe tomake dekhte jabo sei bikele tomar pashe bose asi ami tumi nei keno amar pashe. Kothay je chile geso evabe amake eka fele ore manoare.
					</p>
				</div> <!-- .col-md-4 col-sm-6 ends -->
			</div> <!-- .row section-content ends -->
		</div><!-- .container ends -->
	</section>

	<div class="row">
		<div class="col s12 m12">
			<img src="{{ URL::asset('img/presentation-footer.jpg') }}" width="100%">
		</div>
	</div>
	<div class="row presentation">
		<div class="col s12 m12">
			<p>{!! $accroche->content !!}</p>
		</div>
	</div>

</div>
@stop

resources/views/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div>
                <p style="color:white; font-size:25px;">John Doe</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> En ligne</a>
            </div>
        </div>



        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">MENUS</li>
            <li class="treeview">
                <a href="/admin/#"><span>Statistiques Site</span> 
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/admin/stats/D">Aujourd'hui</a></li>
                    <li><a href="/admin/stats/W">Semaine</a></li>
                    <li><a href="/admin/stats/M">Mois</a></li>
                    <li><a href="/admin/stats/Y">Année</a></li>
                </ul>
            </li>
            <li><a href="/admin/user"><span>Gestion des utilisateurs</span></a></li>
            <li><a href="/admin/pages"><span>Gestion des pages</span></a></li>
            <li><a href="/admin/abonnements"><span>Gestion des abonnements</span></a></li>
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/userinfos.blade.php
Type d'abonnement : {{ $subscription or 'N/A' }}<br>
Nombre de collaborateurs : {{ $numberUsersCompany or 'N/A' }}<br>
Temps de connexion aujourd'hui : {{{ $timeToday or 'N/A' }}}